
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'SeasoningManagement'
project './SeasoningManagement/SeasoningManagement'
platform :ios, '13.0'

def shared_pod
    pod 'RxSwift' , '~> 5'
    pod 'RxCocoa', '~> 5'
end

def test_shared_pod
    pod 'RxBlocking', '~> 5'
    pod 'RxTest', '~> 5'
end


target 'SeasoningManagement' do
  use_frameworks!
  
  pod 'LicensePlist'
  shared_pod
  
  target 'SeasoningManagementTests' do
    inherit! :search_paths
    # Pods for testing
    shared_pod
  end

end
